package com.auge.execute.message;

/**
 * Created by lixun on 2017/6/22.
 */
public enum MessageType {
    JOB_SUBMIT, JOB_SUCCESS, JOB_FAILURE, JOB_UNKNOWN, MASTER_EXECUTE, MASTER_CONNECT_SUCCESS, WORKER_SUCCESS, WORKER_FAILURE, WORKER_CONNECT_EXECUTOR
}
